project:
  type: website
  output-dir: docs

website:
  title: "Aaron Lam"
  navbar:
    left:
      - href: index.qmd
        text: About
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

